/* tslint:disable */
/* eslint-disable */
/**
 * ResilientDB API
 * Key-Value Querying Interface for ResilientDB
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCollectionRequestOptions } from './CreateCollectionRequestOptions';
import {
    CreateCollectionRequestOptionsFromJSON,
    CreateCollectionRequestOptionsFromJSONTyped,
    CreateCollectionRequestOptionsToJSON,
    CreateCollectionRequestOptionsToJSONTyped,
} from './CreateCollectionRequestOptions';
import type { CreateCollectionRequestSchema } from './CreateCollectionRequestSchema';
import {
    CreateCollectionRequestSchemaFromJSON,
    CreateCollectionRequestSchemaFromJSONTyped,
    CreateCollectionRequestSchemaToJSON,
    CreateCollectionRequestSchemaToJSONTyped,
} from './CreateCollectionRequestSchema';

/**
 * 
 * @export
 * @interface CreateCollectionRequest
 */
export interface CreateCollectionRequest {
    /**
     * Name of the collection to create
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    collectionName: string;
    /**
     * 
     * @type {CreateCollectionRequestOptions}
     * @memberof CreateCollectionRequest
     */
    options: CreateCollectionRequestOptions;
    /**
     * 
     * @type {CreateCollectionRequestSchema}
     * @memberof CreateCollectionRequest
     */
    schema: CreateCollectionRequestSchema;
}

/**
 * Check if a given object implements the CreateCollectionRequest interface.
 */
export function instanceOfCreateCollectionRequest(value: object): value is CreateCollectionRequest {
    if (!('collectionName' in value) || value['collectionName'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    return true;
}

export function CreateCollectionRequestFromJSON(json: any): CreateCollectionRequest {
    return CreateCollectionRequestFromJSONTyped(json, false);
}

export function CreateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionName': json['collection_name'],
        'options': CreateCollectionRequestOptionsFromJSON(json['options']),
        'schema': CreateCollectionRequestSchemaFromJSON(json['schema']),
    };
}

export function CreateCollectionRequestToJSON(json: any): CreateCollectionRequest {
    return CreateCollectionRequestToJSONTyped(json, false);
}

export function CreateCollectionRequestToJSONTyped(value?: CreateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_name': value['collectionName'],
        'options': CreateCollectionRequestOptionsToJSON(value['options']),
        'schema': CreateCollectionRequestSchemaToJSON(value['schema']),
    };
}

