/* tslint:disable */
/* eslint-disable */
/**
 * ResilientDB API
 * Key-Value Querying Interface for ResilientDB
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCollectionResponse
 */
export interface CreateCollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionResponse
     */
    status?: CreateCollectionResponseStatusEnum;
    /**
     * Success message
     * @type {string}
     * @memberof CreateCollectionResponse
     */
    message?: string;
}


/**
 * @export
 */
export const CreateCollectionResponseStatusEnum = {
    Success: 'success'
} as const;
export type CreateCollectionResponseStatusEnum = typeof CreateCollectionResponseStatusEnum[keyof typeof CreateCollectionResponseStatusEnum];


/**
 * Check if a given object implements the CreateCollectionResponse interface.
 */
export function instanceOfCreateCollectionResponse(value: object): value is CreateCollectionResponse {
    return true;
}

export function CreateCollectionResponseFromJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseFromJSONTyped(json, false);
}

export function CreateCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CreateCollectionResponseToJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseToJSONTyped(json, false);
}

export function CreateCollectionResponseToJSONTyped(value?: CreateCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

