/* tslint:disable */
/* eslint-disable */
/**
 * ResilientDB API
 * Key-Value Querying Interface for ResilientDB
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCollectionRequestOptions
 */
export interface CreateCollectionRequestOptions {
    /**
     * Primary key field name
     * @type {string}
     * @memberof CreateCollectionRequestOptions
     */
    primaryKey?: string;
    /**
     * Secondary key field name
     * @type {string}
     * @memberof CreateCollectionRequestOptions
     */
    secondaryKey?: string;
    /**
     * Filter policy for the collection
     * @type {string}
     * @memberof CreateCollectionRequestOptions
     */
    filterPolicy?: string;
    /**
     * Filter policy bits per key
     * @type {number}
     * @memberof CreateCollectionRequestOptions
     */
    filterPolicyBitsPerKey?: number;
}

/**
 * Check if a given object implements the CreateCollectionRequestOptions interface.
 */
export function instanceOfCreateCollectionRequestOptions(value: object): value is CreateCollectionRequestOptions {
    return true;
}

export function CreateCollectionRequestOptionsFromJSON(json: any): CreateCollectionRequestOptions {
    return CreateCollectionRequestOptionsFromJSONTyped(json, false);
}

export function CreateCollectionRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryKey': json['primary_key'] == null ? undefined : json['primary_key'],
        'secondaryKey': json['secondary_key'] == null ? undefined : json['secondary_key'],
        'filterPolicy': json['filter_policy'] == null ? undefined : json['filter_policy'],
        'filterPolicyBitsPerKey': json['filter_policy_bits_per_key'] == null ? undefined : json['filter_policy_bits_per_key'],
    };
}

export function CreateCollectionRequestOptionsToJSON(json: any): CreateCollectionRequestOptions {
    return CreateCollectionRequestOptionsToJSONTyped(json, false);
}

export function CreateCollectionRequestOptionsToJSONTyped(value?: CreateCollectionRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary_key': value['primaryKey'],
        'secondary_key': value['secondaryKey'],
        'filter_policy': value['filterPolicy'],
        'filter_policy_bits_per_key': value['filterPolicyBitsPerKey'],
    };
}

